name: E2E Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  e2e-test:
    name: E2E Test - ${{ matrix.distro.test-name }}
    runs-on: windows-latest
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        distro:
          - name: "Ubuntu 22.04 LTS"
            test-name: "ubuntu-2204-test"
          - name: "Debian"
            test-name: "debian-test"
          - name: "Ubuntu 24.04 LTS"
            test-name: "ubuntu-2404-test"
          - name: "Kali Linux"
            test-name: "kali-test"
          - name: "openSUSE Tumbleweed"
            test-name: "opensuse-tumbleweed-test"
          - name: "Oracle Linux 9.5"
            test-name: "oracle-9-test"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\go-build
            ~\go\pkg\mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - name: Setup WSL
        uses: Vampire/setup-wsl@v6
      
      - name: Build autowsl
        run: go build -o autowsl.exe .
      
      - name: Verify WSL
        run: wsl --status
        shell: pwsh
        continue-on-error: true
      
      - name: Install and provision
        shell: pwsh
        timeout-minutes: 30
        run: |
          .\autowsl.exe install "${{ matrix.distro.name }}" --name "${{ matrix.distro.test-name }}"
          .\autowsl.exe provision "${{ matrix.distro.test-name }}" --playbooks systemd
          .\autowsl.exe provision "${{ matrix.distro.test-name }}" --playbooks ssh --extra-vars ssh_port=2222
          .\autowsl.exe copy "${{ matrix.distro.test-name }}" --name "${{ matrix.distro.test-name }}-copy"
          
      - name: Verify install
        shell: pwsh
        run: |
          $name = "${{ matrix.distro.test-name }}"
          $copyName = "${{ matrix.distro.test-name }}-copy"
          $listOutput = ./autowsl.exe list
          if ($listOutput -match $name -and $listOutput -match $copyName) {
            Write-Host "✓ Distro '$name' and '$copyName' successfully verified in output."
          } else {
            Write-Host "--- Full 'autowsl list' output ---"
            Write-Host $listOutput
            Write-Host "------------------------------------"
            Write-Host "ERROR: Distro '$name' or '$copyName' was not found in the list!"
            exit 1
          }

      - name: Verify SSH and Systemd
        run: |
          wsl -d "${{ matrix.distro.test-name }}" -- systemctl status ssh
          wsl -d "${{ matrix.distro.test-name }}" -- grep "Port 2222" /etc/ssh/sshd_config
        shell: pwsh
        continue-on-error: true
      
      - name: Diagnostics on failure
        if: failure()
        shell: pwsh
        run: |
          wsl -l -v || $true
          wsl --status || $true
          Get-ChildItem -Recurse .autowsl_tmp 2>$null | Select-Object FullName,Length || $true
      - name: Cleanup
        if: always()
        shell: pwsh
        run: |
          wsl --unregister "${{ matrix.distro.test-name }}" 2>$null || $true
          wsl --unregister "${{ matrix.distro.test-name }}-copy" 2>$null || $true
