name: E2E Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  e2e-test:
    name: E2E Test - ${{ matrix.distro.test-name }}
    runs-on: windows-latest
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        distro:
          - name: "Ubuntu 22.04 LTS"
            test-name: "ubuntu-2204-test"
          - name: "Debian"
            test-name: "debian-test"
          - name: "Ubuntu 24.04 LTS"
            test-name: "ubuntu-2404-test"
          - name: "Kali Linux"
            test-name: "kali-test"
          - name: "openSUSE Tumbleweed"
            test-name: "opensuse-tumbleweed-test"
          - name: "Oracle Linux 9.5"
            test-name: "oracle-9-test"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\go-build
            ~\go\pkg\mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - name: Setup WSL
        uses: Vampire/setup-wsl@v6
      
      - name: Build autowsl
        run: go build -o autowsl.exe .
      
      - name: Verify WSL
        run: wsl --status
        shell: pwsh
        continue-on-error: true
      
      - name: Install and provision
        shell: pwsh
        timeout-minutes: 30
        run: |
          .\autowsl.exe install "${{ matrix.distro.name }}" --name "${{ matrix.distro.test-name }}" --playbooks curl
      
      - name: Verify install
        shell: pwsh
        run: |
          $name='${{ matrix.distro.test-name }}'
          wsl -l -v
          if ((wsl -l -v) -notmatch $name) { Write-Host "Distro $name not found"; exit 1 }
      
      - name: Verify curl
        run: wsl -d "${{ matrix.distro.test-name }}" -- curl --version
        shell: pwsh
      
      - name: Test curl
        run: wsl -d "${{ matrix.distro.test-name }}" -- curl -s https://www.google.com
        shell: pwsh
      
      - name: Diagnostics on failure
        if: failure()
        shell: pwsh
        run: |
          wsl -l -v || $true
          wsl --status || $true
          Get-ChildItem -Recurse .autowsl_tmp 2>$null | Select-Object FullName,Length || $true
      - name: Cleanup
        if: always()
        shell: pwsh
        run: |
          wsl --unregister "${{ matrix.distro.test-name }}" 2>$null || $true
