name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    env:
      GO_VERSION: '1.21'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Get version
        id: version
        run: |
          if ("${{ github.ref_name }}") {
            echo "VERSION=${{ github.ref_name }}" >> $env:GITHUB_OUTPUT
          }
        shell: pwsh
      
      - name: Build
        shell: pwsh
        run: |
          $VERSION = "${{ steps.version.outputs.VERSION }}"
          go build -ldflags "-X github.com/yuanjua/autowsl/cmd.Version=$VERSION" -o autowsl-windows-amd64.exe .
          $env:GOARCH = "arm64"
          go build -ldflags "-X github.com/yuanjua/autowsl/cmd.Version=$VERSION" -o autowsl-windows-arm64.exe .
      
      - name: Checksums
        run: |
          Get-FileHash autowsl-windows-*.exe | ForEach-Object {
            "$($_.Hash.ToLower())  $($_.Path | Split-Path -Leaf)"
          } | Out-File checksums.txt
        shell: pwsh
      
      - name: Upload build artifacts (debug)
        uses: actions/upload-artifact@v4
        with:
          name: release-build-${{ steps.version.outputs.VERSION }}
          path: |
            autowsl-windows-*.exe
            checksums.txt
          retention-days: 5
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: ${{ contains(github.ref_name, '-') }}
          prerelease: ${{ contains(github.ref_name, '-') }}
          files: |
            autowsl-windows-amd64.exe
            autowsl-windows-arm64.exe
            checksums.txt

